version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_WS_URL=ws://localhost:7788/ws
      - NEXT_PUBLIC_API_URL=http://localhost:7788/api
    depends_on:
      - backend

  backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "7788:7788"
      - "6080:6080"  # VNC Viewer port
    volumes:
      - ./python:/app
      - ./tmp:/app/tmp
    environment:
      - PYTHONUNBUFFERED=1
      - CHROME_PERSISTENT_SESSION=${CHROME_PERSISTENT_SESSION:-false}
      - VNC_PASSWORD=${VNC_PASSWORD:-vncpassword}
      - RESOLUTION=${RESOLUTION:-1920x1080x24}
      - RESOLUTION_WIDTH=${RESOLUTION_WIDTH:-1920}
      - RESOLUTION_HEIGHT=${RESOLUTION_HEIGHT:-1080}
    cap_add:
      - SYS_ADMIN  # Required for Chrome
    shm_size: '2gb'  # Required for Chrome to avoid crashes

networks:
  default:
    driver: bridge